version: '3.9'

services:
  shop-db:
    image: postgres
    container_name: shop-db
    restart: always
    environment:
      POSTGRES_USER: bym
      POSTGRES_PASSWORD: bym
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data-volume:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"